a = input("Digite algo:")
print('O tipo primitivo desse valo é',type(a))
print ('Só tem espaço?',a.isspace())
print ('É um numero?', a.isnumeric())
print ('É alfabetico?',a.isalpha())
print ('É alfanumerico?',a.isalnum())
print ('Esta em maiuscula?',a.isupper())
print ('Esta em minuscula?',a.islower())
print ('Esta capitalizada?', a.istitle())
