n1 = float(input('Digite o primeiro numero:'))
n2 = float(input('Digite o segundo numero:'))
n3 = float(input('Digite o terceiro numero:'))
maior = max(n1, n2, n3)
menor = min(n1, n2, n3)
print(f'O maior número é {maior}')
print(f'O menor número é {menor}')